apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260627-234615-wovkeqeegyrr-service
spec:
  selector:
    app: enterprise-system-20260627-234615-wovkeqeegyrr
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
